apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app_name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}
    spec:
      {{- if and .Values.serviceAccount.enabled .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      {{- end }}
      containers:
        - name: {{ .Values.app_name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.port }}
          {{- if .Values.env }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          {{- end }}
