apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.app_name }}-service"
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.app_name }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  type: {{ .Values.service_type }}