app_name: resume-backend
namespace: resume
port: 8000
service_type: ClusterIP
replicaCount: 2

image:
  repository: 570082719665.dkr.ecr.us-east-1.amazonaws.com/resume-backend
  tag: latest

ingress:
  enabled: false

serviceAccount:
  enabled: false
  create: false
  name: ""
  roleArn: ""
